-- Základná štruktúra a dátový model mediacentra.
-- Index je jediné, z čoho číta REST API — Samba sa pri obsluhe requestu nikdy neskenuje.
--
-- Model má tri entity:
--   smb_source  … odkiaľ sa médiá berú (nastavuje sa z management UI)
--   media_item  … čo sken našiel; toto vidí Android TV klient
--   scan_run    … kedy a s akým výsledkom sken bežal

-- Zdroj médií. Prihlasovacie údaje drží výhradne server, klient sa na Sambu nepripája.
CREATE TABLE smb_source
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255)             NOT NULL,
    host       VARCHAR(255)             NOT NULL,
    port       INTEGER                  NOT NULL DEFAULT 445,
    share_name VARCHAR(255)             NOT NULL,
    -- Podpriečinok v rámci share-u; prázdny reťazec znamená celý share.
    root_path  VARCHAR(1024)            NOT NULL DEFAULT '',
    domain     VARCHAR(255),
    username   VARCHAR(255),
    -- Von sa nedostane cez žiadne DTO, šablónu ani toString().
    password   VARCHAR(512),
    enabled    BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Indexovaný súbor.
CREATE TABLE media_item
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id         BIGINT                   NOT NULL REFERENCES smb_source (id) ON DELETE CASCADE,
    -- VIDEO / PHOTO / AUDIO — tri dlaždice, ktoré vidí používateľ na TV.
    category          VARCHAR(16)              NOT NULL,
    -- Cesta voči koreňu zdroja, oddeľovač '/', bez úvodnej lomky.
    relative_path     VARCHAR(2048)            NOT NULL,
    file_name         VARCHAR(512)             NOT NULL,
    title             VARCHAR(512)             NOT NULL,
    extension         VARCHAR(32)              NOT NULL,
    size_bytes        BIGINT                   NOT NULL,
    modified_at       TIMESTAMP WITH TIME ZONE,
    content_type      VARCHAR(128)             NOT NULL,
    -- Sken, ktorý súbor videl naposledy. Čo po skene ostane staré, sa vymaže.
    last_seen_scan_id BIGINT,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Cesta v rámci zdroja je identita položky — na nej stojí upsert pri skene.
CREATE UNIQUE INDEX ux_media_item_path ON media_item (source_id, relative_path);
CREATE INDEX ix_media_item_category ON media_item (category, title);
CREATE INDEX ix_media_item_scan ON media_item (source_id, last_seen_scan_id);

-- História skenov; riadok vzniká na začiatku a priebežne sa dopĺňa, aby UI videlo postup.
CREATE TABLE scan_run
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id           BIGINT REFERENCES smb_source (id) ON DELETE CASCADE,
    -- MANUAL / SCHEDULED / STARTUP
    trigger_type        VARCHAR(16)              NOT NULL,
    -- RUNNING / COMPLETED / FAILED
    status              VARCHAR(16)              NOT NULL,
    started_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at         TIMESTAMP WITH TIME ZONE,
    directories_scanned INTEGER                  NOT NULL DEFAULT 0,
    files_seen          INTEGER                  NOT NULL DEFAULT 0,
    items_added         INTEGER                  NOT NULL DEFAULT 0,
    items_updated       INTEGER                  NOT NULL DEFAULT 0,
    items_removed       INTEGER                  NOT NULL DEFAULT 0,
    error_message       VARCHAR(2048)
);

CREATE INDEX ix_scan_run_started ON scan_run (started_at DESC);
