-- Base media center structure and data model.
-- The REST API reads exclusively from the index; Samba is never scanned while handling requests.
--
-- The model has three entities:
--   smb_source  ... where media comes from (configured in the management UI)
--   media_item  ... what a scan found; visible to the Android TV client
--   scan_run    ... when a scan ran and its result

-- Media source. Only the server holds credentials; the client does not connect to Samba.
CREATE TABLE smb_source
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255)             NOT NULL,
    host       VARCHAR(255)             NOT NULL,
    port       INTEGER                  NOT NULL DEFAULT 445,
    share_name VARCHAR(255)             NOT NULL,
    -- Subdirectory within the share; an empty string means the entire share.
    root_path  VARCHAR(1024)            NOT NULL DEFAULT '',
    domain     VARCHAR(255),
    username   VARCHAR(255),
    -- Never exposed through a DTO, template, or toString().
    password   VARCHAR(512),
    enabled    BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Indexed file.
CREATE TABLE media_item
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id         BIGINT                   NOT NULL REFERENCES smb_source (id) ON DELETE CASCADE,
    -- VIDEO / PHOTO / AUDIO: the three tiles visible to the TV user.
    category          VARCHAR(16)              NOT NULL,
    -- Path relative to the source root, using '/' separators and no leading slash.
    relative_path     VARCHAR(2048)            NOT NULL,
    file_name         VARCHAR(512)             NOT NULL,
    title             VARCHAR(512)             NOT NULL,
    extension         VARCHAR(32)              NOT NULL,
    size_bytes        BIGINT                   NOT NULL,
    modified_at       TIMESTAMP WITH TIME ZONE,
    content_type      VARCHAR(128)             NOT NULL,
    -- Scan that most recently saw the file. Anything left stale after a scan is deleted.
    last_seen_scan_id BIGINT,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL
);

-- A path within a source identifies an item and is the basis of scan upserts.
CREATE UNIQUE INDEX ux_media_item_path ON media_item (source_id, relative_path);
CREATE INDEX ix_media_item_category ON media_item (category, title);
CREATE INDEX ix_media_item_scan ON media_item (source_id, last_seen_scan_id);

-- Scan history; a row is created at the start and updated so the UI can show progress.
CREATE TABLE scan_run
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id           BIGINT REFERENCES smb_source (id) ON DELETE CASCADE,
    -- MANUAL / SCHEDULED / STARTUP
    trigger_type        VARCHAR(16)              NOT NULL,
    -- RUNNING / COMPLETED / FAILED
    status              VARCHAR(16)              NOT NULL,
    started_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at         TIMESTAMP WITH TIME ZONE,
    directories_scanned INTEGER                  NOT NULL DEFAULT 0,
    files_seen          INTEGER                  NOT NULL DEFAULT 0,
    items_added         INTEGER                  NOT NULL DEFAULT 0,
    items_updated       INTEGER                  NOT NULL DEFAULT 0,
    items_removed       INTEGER                  NOT NULL DEFAULT 0,
    error_message       VARCHAR(2048)
);

CREATE INDEX ix_scan_run_started ON scan_run (started_at DESC);
