-- Prihlasovanie a správa používateľov.
--
-- Dve roly:
--   ADMIN … management UI v prehliadači aj Android klient
--   USER  … výhradne Android klient, do /admin sa nedostane
--
-- Dva spôsoby prihlásenia:
--   heslo … povinné, platí všade
--   PIN   … nepovinný, len pre Android klienta (na diaľkovom ovládači sa heslo píše zle)

CREATE TABLE app_user
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Ukladá sa vždy malými písmenami, aby bolo prihlásenie necitlivé na veľkosť
    -- písmen bez funkcionálneho indexu.
    username             VARCHAR(64)              NOT NULL,
    display_name         VARCHAR(255)             NOT NULL,
    -- Argon2id, formát $argon2id$v=19$m=...,t=...,p=...$salt$hash — soľ je súčasťou reťazca.
    password_hash        VARCHAR(255)             NOT NULL,
    -- NULL = používateľ PIN nastavený nemá a prihlásiť sa ním nemôže.
    pin_hash             VARCHAR(255),
    -- ADMIN / USER
    role                 VARCHAR(16)              NOT NULL,
    enabled              BOOLEAN                  NOT NULL DEFAULT TRUE,
    -- Prvý admin sa zakladá s admin/admin; kým si heslo nezmení, UI ho inam nepustí.
    must_change_password BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX ux_app_user_username ON app_user (username);

-- Prihlasovací token Android klienta. Klient si po prihlásení neukladá heslo ani PIN,
-- len tento token — a ten sa dá zo servera zneplatniť.
CREATE TABLE auth_token
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT                   NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    -- SHA-256 samotného tokenu v hex tvare, nie token samotný. Argon2 sa sem nehodí —
    -- overuje sa pri každom requeste a token je 256-bitové náhodné číslo, takže
    -- pomalé hashovanie proti hádaniu nič nerieši.
    token_hash   CHAR(64)                 NOT NULL,
    -- Čo si používateľ pri prihlásení pomenoval ako zariadenie (napr. "Obývačka").
    device_name  VARCHAR(255),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    last_used_at TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX ux_auth_token_hash ON auth_token (token_hash);
CREATE INDEX ix_auth_token_user ON auth_token (user_id);
CREATE INDEX ix_auth_token_expires ON auth_token (expires_at);
