-- Authentication and user management.
--
-- Two roles:
--   ADMIN ... browser-based management UI and Android client
--   USER  ... Android client only, with no access to /admin
--
-- Two authentication methods:
--   password ... required and valid everywhere
--   PIN      ... optional and Android-only (password entry with a remote control is awkward)

CREATE TABLE app_user
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Always stored in lowercase to provide case-insensitive login without a functional index.
    username             VARCHAR(64)              NOT NULL,
    display_name         VARCHAR(255)             NOT NULL,
    -- Argon2id format: $argon2id$v=19$m=...,t=...,p=...$salt$hash; the salt is part of the string.
    password_hash        VARCHAR(255)             NOT NULL,
    -- NULL means the user has no PIN and cannot use one to log in.
    pin_hash             VARCHAR(255),
    -- ADMIN / USER
    role                 VARCHAR(16)              NOT NULL,
    enabled              BOOLEAN                  NOT NULL DEFAULT TRUE,
    -- The initial administrator is created as admin/admin; the UI is blocked until it is changed.
    must_change_password BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX ux_app_user_username ON app_user (username);

-- Android client authentication token. After login, the client stores neither the password
-- nor PIN, only this token, which can be invalidated by the server.
CREATE TABLE auth_token
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT                   NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    -- SHA-256 of the token in hexadecimal form, not the token itself. Argon2 is unsuitable:
    -- verification runs on every request, and the token is a random 256-bit number, so a slow
    -- hash adds no protection against guessing.
    token_hash   CHAR(64)                 NOT NULL,
    -- Device name supplied by the user during login (for example, "Living Room").
    device_name  VARCHAR(255),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    last_used_at TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX ux_auth_token_hash ON auth_token (token_hash);
CREATE INDEX ix_auth_token_user ON auth_token (user_id);
CREATE INDEX ix_auth_token_expires ON auth_token (expires_at);
