-- Filmové metadáta z verejného katalógu, žánre a poradie seriálov/viacdielnych videí.
-- Pôvodná `category` ostáva VIDEO / PHOTO / AUDIO pre tri dlaždice Android TV klienta;
-- žáner je samostatná mnohonásobná klasifikácia (film môže byť zároveň komédia aj sci-fi).

ALTER TABLE media_item ADD COLUMN video_kind VARCHAR(16);
ALTER TABLE media_item ADD COLUMN metadata_provider VARCHAR(32);
ALTER TABLE media_item ADD COLUMN provider_id BIGINT;
ALTER TABLE media_item ADD COLUMN description VARCHAR(10000);
ALTER TABLE media_item ADD COLUMN poster_file VARCHAR(512);
ALTER TABLE media_item ADD COLUMN release_year INTEGER;
ALTER TABLE media_item ADD COLUMN rating NUMERIC(3, 1);
ALTER TABLE media_item ADD COLUMN group_key VARCHAR(255);
ALTER TABLE media_item ADD COLUMN group_title VARCHAR(512);
ALTER TABLE media_item ADD COLUMN season_number INTEGER;
ALTER TABLE media_item ADD COLUMN episode_number INTEGER;
ALTER TABLE media_item ADD COLUMN part_number INTEGER;
ALTER TABLE media_item ADD COLUMN metadata_status VARCHAR(16) NOT NULL DEFAULT 'SKIPPED';
ALTER TABLE media_item ADD COLUMN metadata_updated_at TIMESTAMP WITH TIME ZONE;

-- Existujúce videá sa obohatia pri najbližšom skene. Fotky a hudba filmové metadáta
-- nepotrebujú, preto ostávajú SKIPPED.
UPDATE media_item SET metadata_status = 'PENDING' WHERE category = 'VIDEO';

CREATE TABLE media_genre
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider    VARCHAR(32)  NOT NULL,
    provider_id BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX ux_media_genre_provider ON media_genre (provider, provider_id);

CREATE TABLE media_item_genre
(
    media_item_id BIGINT NOT NULL REFERENCES media_item (id) ON DELETE CASCADE,
    genre_id      BIGINT NOT NULL REFERENCES media_genre (id) ON DELETE CASCADE,
    PRIMARY KEY (media_item_id, genre_id)
);

CREATE INDEX ix_media_item_genre_genre ON media_item_genre (genre_id, media_item_id);
CREATE INDEX ix_media_item_group_order
    ON media_item (group_key, season_number, episode_number, part_number);
CREATE INDEX ix_media_item_metadata_due ON media_item (category, metadata_status, metadata_updated_at);
